# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MSBuild

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Clone PluginSDK
      run: git clone https://github.com/DK22Pac/plugin-sdk ${{runner.temp}}/pluginsdk

    - name: Set PLUGIN_SDK_DIR
      run: $env:PLUGIN_SDK_DIR="${{runner.temp}}/pluginsdk"

    - name: Set GitHub PLUGIN_SDK_DIR
      run: echo "PLUGIN_SDK_DIR=${{runner.temp}}/pluginsdk" | Out-File -FilePath $env:GITHUB_ENV

    - name: Generate PluginSDK for vs2022
      run: ${{runner.temp}}/pluginsdk/tools/premake/premake5.exe vs2022 --file="${{runner.temp}}/pluginsdk/tools/premake/premake5.lua"

    - name: Build PluginSDK
      working-directory: ${{runner.temp}}/pluginsdk
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=Release /property:Platform=Win32 plugin_sa/plugin_sa.vcxproj

    - name: Build plugin
      working-directory: ${{env.GITHUB_WORKFLOW}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AutoHealSA
        path: /bin/
      
