# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: NuMake

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

env:
    # Path to the solution file relative to the root of the project.
    SOLUTION_FILE_PATH: AutoHealSA/AutoHealSA.vcxproj

    # Configuration type to build.
    # You can convert this to a build matrix if you need coverage of multiple configuration types.
    # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    BUILD_CONFIGURATION: Release

    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-24.04

        steps:
            - uses: actions/checkout@v4

            - name: Download numake
              run: |
                  gh release download indev -R juicermv/numake --dir "${{runner.temp}}"
                  chmod a+x "${{runner.temp}}"/numake

            - name: Build using numake
              working-directory: ${{env.GITHUB_WORKFLOW}}
              run: ."${{runner.temp}}/numake" build all

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: AutoHealSA
                  path: ./.numake/out/AutoHealSA
